<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>6.2211.v27f680c93c53</version>
  </parent>

  <groupId>io.jenkins.plugins</groupId>
  <artifactId>controller-clock</artifactId>
  <version>${revision}.${changelist}</version>
  <packaging>hpi</packaging>

  <name>Controller Clock</name>
  <description>Displays the Jenkins controller time and timezone in the UI.</description>
  <url>https://github.com/jenkinsci/controller-clock-plugin</url>

  <properties>
    <revision>0.1</revision>
    <changelist>999999-SNAPSHOT</changelist>
    <jenkins.baseline>2.541</jenkins.baseline>
    <jenkins.version>${jenkins.baseline}.3</jenkins.version>
    <hpi.strictBundledArtifacts>true</hpi.strictBundledArtifacts>
    <banObsoleteDependencyOverrides.skip>false</banObsoleteDependencyOverrides.skip>
    <ban-junit4-imports.skip>false</ban-junit4-imports.skip>
    <ban-deprecated-stapler.skip>false</ban-deprecated-stapler.skip>
    <ban-commons-lang-2.skip>false</ban-commons-lang-2.skip>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
        <artifactId>bom-${jenkins.baseline}.x</artifactId>
        <version>6931.vea_a_b_c6fd017d</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:https://github.com/jenkinsci/controller-clock-plugin.git</connection>
    <developerConnection>scm:git:https://github.com/jenkinsci/controller-clock-plugin.git</developerConnection>
    <url>https://github.com/jenkinsci/controller-clock-plugin</url>
  </scm>

  <repositories>
    <repository>
      <id>jenkins-public</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>jenkins-public</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

  <dependencies>
    <dependency>
      <groupId>io.jenkins.plugins</groupId>
      <artifactId>ionicons-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kohsuke</groupId>
      <artifactId>access-modifier-suppressions</artifactId>
      <version>${access-modifier-checker.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
